# Generated by Django 4.1.2 on 2023-02-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='category_connection',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post',
            new_name='post_connection',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(related_name='post', through='news.PostCategory', to='news.category'),
        ),
    ]
