# Generated by Django 4.1.2 on 2023-02-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_category_postcategory_category_connection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='category_connection',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='post_connection',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category'),
        ),
    ]
